# This file was generated by GoReleaser. DO NOT EDIT.
cask "yakanban" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "ca052e3a47d3df85b09246782e492a5ad7d2d108e5ff6b26bdd73757c93e82c2"
      url "https://github.com/aramponi/yakanban/releases/download/v#{version}/yakanban_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1e72d9f990480b5e601d076890068b7ba1c7c6b16b08e6aa03547fa931852b0a"
      url "https://github.com/aramponi/yakanban/releases/download/v#{version}/yakanban_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "335fafdbf19ac309818363f977c5bed66ab3ee22f0d67748f655a44d96b8bebf"
      url "https://github.com/aramponi/yakanban/releases/download/v#{version}/yakanban_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ed4a370352b2f9da8e363d2a1f8fa03b0022bc56835949c087e195770c04ec1b"
      url "https://github.com/aramponi/yakanban/releases/download/v#{version}/yakanban_#{version}_linux_amd64.tar.gz"
    end
  end

  name "yakanban"
  desc "Kanban over your real ticket tracker, for humans and AI agents"
  homepage "https://github.com/aramponi/yakanban"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yakanban"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yakanban"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    yakanban authenticates through the GitHub CLI. If you have not already:

      gh auth login
      gh auth refresh -s project   # Projects v2 needs its own scope
  EOS
end
