# This file was generated by GoReleaser. DO NOT EDIT.
cask "yakanban" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "e381197b4bfbaee0131ae99de631bcf57d67010f5d3d75a036e0e6d6bcc1f77f"
      url "https://github.com/aramponi/yakanban/releases/download/v#{version}/yakanban_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "83d1b605acbd98961ee34afba5d16cf9c7d8351b0930d7422968cd9478fb6c2b"
      url "https://github.com/aramponi/yakanban/releases/download/v#{version}/yakanban_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a8ff1ed5d13c072d0f8968795cbab9ce3a0719bc5cca15fce07223c0692e5bee"
      url "https://github.com/aramponi/yakanban/releases/download/v#{version}/yakanban_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "89c736e288a9e9ef7e97194ee86613d4d5833c110e04345c6aa57998da9c2560"
      url "https://github.com/aramponi/yakanban/releases/download/v#{version}/yakanban_#{version}_linux_amd64.tar.gz"
    end
  end

  name "yakanban"
  desc "Kanban over your real ticket tracker, for humans and AI agents"
  homepage "https://github.com/aramponi/yakanban"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yakanban"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yakanban"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    yakanban authenticates through the GitHub CLI. If you have not already:

      gh auth login
      gh auth refresh -s project   # Projects v2 needs its own scope
  EOS
end
