# This file was generated by GoReleaser. DO NOT EDIT.
cask "yakanban" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "679d25fc9dac8cf4beca3e38558695d2fda7ae3ec7deb87f8169b1dcf84dcaa0"
      url "https://github.com/aramponi/yakanban/releases/download/v#{version}/yakanban_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a9bf6901a6118fb7ba9db47e4bdf5122ea87373c4d2a8d970bbb6a428fedfc56"
      url "https://github.com/aramponi/yakanban/releases/download/v#{version}/yakanban_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "90cc48653d89e3540cc2b67102d720596131b6e1db7fae1df57f1dd0a4cb53db"
      url "https://github.com/aramponi/yakanban/releases/download/v#{version}/yakanban_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ebccad6a0ac6b2619d95efb8a69ef0b86a2dce383cec8b313bff2f0dfe6b36a"
      url "https://github.com/aramponi/yakanban/releases/download/v#{version}/yakanban_#{version}_linux_amd64.tar.gz"
    end
  end

  name "yakanban"
  desc "Kanban over your real ticket tracker, for humans and AI agents"
  homepage "https://github.com/aramponi/yakanban"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yakanban"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yakanban"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    yakanban authenticates through the GitHub CLI. If you have not already:

      gh auth login
      gh auth refresh -s project   # Projects v2 needs its own scope
  EOS
end
